<?php
/**
 * Delivery
 *
 * PHP version 5
 *
 * @category Class
 * @package  iPOS
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iPOS REST Service
 *
 * Api for connecting to iPOS (FileMaker 16)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace iPOS\Model;

use \ArrayAccess;
use \iPOS\ObjectSerializer;

/**
 * Delivery Class Doc Comment
 *
 * @category Class
 * @package     iPOS
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Delivery implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Delivery';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'idUuid' => 'string',
        'idLokation' => 'string',
        'datoOpr' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'idUuid' => null,
        'idLokation' => null,
        'datoOpr' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'idUuid' => 'id_uuid',
        'idLokation' => 'id_lokation',
        'datoOpr' => 'Dato_opr'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'idUuid' => 'setIdUuid',
        'idLokation' => 'setIdLokation',
        'datoOpr' => 'setDatoOpr'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'idUuid' => 'getIdUuid',
        'idLokation' => 'getIdLokation',
        'datoOpr' => 'getDatoOpr'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['idUuid'] = isset($data['idUuid']) ? $data['idUuid'] : null;
        $this->container['idLokation'] = isset($data['idLokation']) ? $data['idLokation'] : null;
        $this->container['datoOpr'] = isset($data['datoOpr']) ? $data['datoOpr'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets idUuid
     *
     * @return string
     */
    public function getIdUuid()
    {
        return $this->container['idUuid'];
    }

    /**
     * Sets idUuid
     *
     * @param string $idUuid idUuid
     *
     * @return $this
     */
    public function setIdUuid($idUuid)
    {
        $this->container['idUuid'] = $idUuid;

        return $this;
    }

    /**
     * Gets idLokation
     *
     * @return string
     */
    public function getIdLokation()
    {
        return $this->container['idLokation'];
    }

    /**
     * Sets idLokation
     *
     * @param string $idLokation idLokation
     *
     * @return $this
     */
    public function setIdLokation($idLokation)
    {
        $this->container['idLokation'] = $idLokation;

        return $this;
    }

    /**
     * Gets datoOpr
     *
     * @return string
     */
    public function getDatoOpr()
    {
        return $this->container['datoOpr'];
    }

    /**
     * Sets datoOpr
     *
     * @param string $datoOpr datoOpr
     *
     * @return $this
     */
    public function setDatoOpr($datoOpr)
    {
        $this->container['datoOpr'] = $datoOpr;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

