<?php
/**
 * ProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iPOS
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iPOS REST Service
 *
 * Api for connecting to iPOS (FileMaker 16)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iPOS;

/**
 * ProductTest Class Doc Comment
 *
 * @category    Class */
// * @description Product
/**
 * @package     iPOS
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Product"
     */
    public function testProduct()
    {

    }

    /**
     * Test attribute "iD"
     */
    public function testPropertyID()
    {

    }

    /**
     * Test attribute "eANNr"
     */
    public function testPropertyEANNr()
    {

    }

    /**
     * Test attribute "varetekst"
     */
    public function testPropertyVaretekst()
    {

    }

    /**
     * Test attribute "vareBeskrivelse"
     */
    public function testPropertyVareBeskrivelse()
    {

    }

    /**
     * Test attribute "varenrLeverandr"
     */
    public function testPropertyVarenrLeverandr()
    {

    }

    /**
     * Test attribute "salgspris"
     */
    public function testPropertySalgspris()
    {

    }

    /**
     * Test attribute "salgsprisInclMoms"
     */
    public function testPropertySalgsprisInclMoms()
    {

    }

    /**
     * Test attribute "kostpris"
     */
    public function testPropertyKostpris()
    {

    }

    /**
     * Test attribute "kostprisDKK"
     */
    public function testPropertyKostprisDKK()
    {

    }

    /**
     * Test attribute "avanceIKr"
     */
    public function testPropertyAvanceIKr()
    {

    }

    /**
     * Test attribute "iDVaregruppe"
     */
    public function testPropertyIDVaregruppe()
    {

    }

    /**
     * Test attribute "lagerStatusNskes"
     */
    public function testPropertyLagerStatusNskes()
    {

    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {

    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {

    }

}
