<?php
/**
 * SalesReportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iPOS
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iPOS REST Service
 *
 * Api for connecting to iPOS (FileMaker 16)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iPOS;

/**
 * SalesReportTest Class Doc Comment
 *
 * @category    Class */
// * @description SalesReport
/**
 * @package     iPOS
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesReportTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SalesReport"
     */
    public function testSalesReport()
    {
    }

    /**
     * Test attribute "antal"
     */
    public function testPropertyAntal()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "sPYAPris"
     */
    public function testPropertySPYAPris()
    {
    }

    /**
     * Test attribute "uIDatoBon"
     */
    public function testPropertyUIDatoBon()
    {
    }

    /**
     * Test attribute "lgIkkePLager"
     */
    public function testPropertyLgIkkePLager()
    {
    }

    /**
     * Test attribute "sPYRelevant"
     */
    public function testPropertySPYRelevant()
    {
    }

    /**
     * Test attribute "sPYDone"
     */
    public function testPropertySPYDone()
    {
    }

    /**
     * Test attribute "idLokation"
     */
    public function testPropertyIdLokation()
    {
    }

    /**
     * Test attribute "taxStateAmount"
     */
    public function testPropertyTaxStateAmount()
    {
    }

    /**
     * Test attribute "taxCityAmount"
     */
    public function testPropertyTaxCityAmount()
    {
    }

    /**
     * Test attribute "taxStateRate"
     */
    public function testPropertyTaxStateRate()
    {
    }

    /**
     * Test attribute "taxCityRate"
     */
    public function testPropertyTaxCityRate()
    {
    }
}
