<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  iPOS
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iPOS REST Service
 *
 * Api for connecting to iPOS (FileMaker 16)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace iPOS;

use \iPOS\Configuration;
use \iPOS\ApiException;
use \iPOS\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  iPOS
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createDelivery
     *
     * Creates a new Delivery.
     *
     */
    public function testCreateDelivery()
    {
    }

    /**
     * Test case for createDeliveryLine
     *
     * Creates a new Delivery Line.
     *
     */
    public function testCreateDeliveryLine()
    {
    }

    /**
     * Test case for createProduct
     *
     * Creates a new product.
     *
     */
    public function testCreateProduct()
    {
    }

    /**
     * Test case for createProductType
     *
     * Creates a new product type.
     *
     */
    public function testCreateProductType()
    {
    }

    /**
     * Test case for findProductByEAN
     *
     * finds a product based on its EAN code.
     *
     */
    public function testFindProductByEAN()
    {
    }

    /**
     * Test case for findProductType
     *
     * finds a product type based on its Id.
     *
     */
    public function testFindProductType()
    {
    }

    /**
     * Test case for findSalesReports
     *
     * finds sales reports.
     *
     */
    public function testFindSalesReports()
    {
    }

    /**
     * Test case for getAllProductTypes
     *
     * retrieves all product types.
     *
     */
    public function testGetAllProductTypes()
    {
    }

    /**
     * Test case for getAllProducts
     *
     * retrieves all products.
     *
     */
    public function testGetAllProducts()
    {
    }

    /**
     * Test case for getDataToken
     *
     * gets an authentication token (valid for 15 minutes).
     *
     */
    public function testGetDataToken()
    {
    }

    /**
     * Test case for getProduct
     *
     * retrieves a product.
     *
     */
    public function testGetProduct()
    {
    }

    /**
     * Test case for getSaleReport
     *
     * retrieves a Sales Report line.
     *
     */
    public function testGetSaleReport()
    {
    }

    /**
     * Test case for markSalesReportAsRead
     *
     * Marks a Sales Report line as Read.
     *
     */
    public function testMarkSalesReportAsRead()
    {
    }

    /**
     * Test case for updateProduct
     *
     * Updates a product.
     *
     */
    public function testUpdateProduct()
    {
    }
}
